### ISSUE TITLE
 喵酱你可以考虑解释一下

### ISSUE THREAD

**Issue by wenxin-bupt** [weicliu/ife-frizz#2]
喵酱已经碉堡了.

**Comment by cececx** [comment]
回头看看这写的都是啥啊……（赶完due认真整理笔记（臣妾再也不敢瞎吐槽了

**Comment by w10u** [comment]
@wenxin-bupt 你的代码呢？就会膜喵。

**Comment by cececx** [comment]
封装继承的解释PO好了~(≧▽≦)/~

**Comment by w10u** [comment]
orz...orz...orz...
orz...orz...orz...
orz...orz...orz...
